"use client";
import { useState } from "react";
import Sidebar from "@/components/dashboard/Sidebar";
import Header from "@/components/dashboard/Header";
type Chat={role:"user"|"assistant";content:string;verified?:boolean};
export default function AITeacherPage(){
 const [message,setMessage]=useState("");const [chat,setChat]=useState<Chat[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
 async function send(text=message){const value=text.trim();if(!value||loading)return;setChat(c=>[...c,{role:"user",content:value}]);setMessage("");setLoading(true);setError("");
  try{const res=await fetch("/api/ai/tutor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:value,subject:"الرياضيات",student:{preferredDialect:"saudi"},history:chat.map(({role,content})=>({role,content})).slice(-6)})});const data=await res.json();if(!res.ok||!data.success)throw new Error(data.message||"تعذر الحصول على الإجابة");setChat(c=>[...c,{role:"assistant",content:data.answer,verified:data.verification?.verified}]);}catch(e){setError(e instanceof Error?e.message:"تعذر الاتصال بالمدرس الذكي");}finally{setLoading(false);}}
 return <div dir="rtl" className="min-h-screen bg-slate-50"><Sidebar/><div className="mr-72 min-h-screen"><Header/><main className="p-6 lg:p-8"><div className="mx-auto max-w-4xl"><h1 className="text-3xl font-bold text-slate-900">مدرس حصة الذكي</h1><p className="mt-2 text-slate-500">نسخة MVP للرياضيات: شرح، حل متحقق للمسائل المدعومة، ومحتوى منهجي أصلي.</p><section className="mt-6 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="min-h-[460px] space-y-4 p-6">{chat.length===0&&<div className="py-20 text-center text-slate-500">اكتب سؤالًا في الرياضيات للبدء.</div>}{chat.map((m,i)=><div key={i} className={m.role==="user"?"mr-auto max-w-[80%] rounded-2xl bg-indigo-600 p-4 text-white":"ml-auto max-w-[85%] rounded-2xl bg-slate-100 p-4 text-slate-800"}><p className="whitespace-pre-wrap leading-7">{m.content}</p>{m.role==="assistant"&&m.verified&&<span className="mt-2 inline-block text-xs font-medium text-emerald-700">✓ تم التحقق حسابيًا</span>}</div>)}{loading&&<div className="text-sm text-slate-500">جاري إعداد الشرح...</div>}{error&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}</div><div className="flex gap-3 border-t p-4"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")send();}} placeholder="مثال: 25% من 80 كم؟" className="flex-1 rounded-2xl border border-slate-200 px-5 py-4 outline-none focus:border-indigo-400"/><button onClick={()=>send()} disabled={loading} className="rounded-2xl bg-indigo-600 px-7 py-4 font-semibold text-white disabled:opacity-50">إرسال</button></div></section></div></main></div></div>;
}