import type{RetrievalDocument,StudentState}from"./types";
export type ConceptResponse={answer:string;concept:string;confidence:number};
export function teachKnownConcept(message:string,student:StudentState={},docs:RetrievalDocument[]=[]):ConceptResponse|null{
 const young=(student.age??99)<=10;
 if(/(?=.*(?:مثلث|مساح))(?=.*(?:ليش|لماذا|ليه|سبب))(?=.*(?:نقسم|قسمة|÷|على\s*2|2))/i.test(message))return{concept:"triangle-area-meaning",confidence:.99,answer:young?"تخيّل مستطيلًا، وارسم خطًا من زاوية إلى الزاوية المقابلة. ينقسم المستطيل إلى مثلثين متساويين. عشان كذا مساحة مثلث واحد هي نصف مساحة المستطيل، فنقسم على 2. جرّب: لو مساحة المستطيل 12، كم مساحة كل مثلث؟":"المثلث الذي له قاعدة وارتفاع محددان يمكن تمثيله كنصف متوازي أضلاع/مستطيل مناسب له القاعدة والارتفاع نفسيهما؛ لذلك مساحة المثلث تساوي نصف حاصل ضرب القاعدة في الارتفاع. القسمة على 2 تأتي من أخذ نصف المساحة، لا من قاعدة محفوظة بلا سبب. هل تريد تمثيلًا عدديًا؟"};
 if(/(?:الكسور|كسر).*?(?:صعب|صعبة|أغلط|اغلط|مو فاهم)|(?:صعب|صعبة|أغلط|اغلط).*?(?:الكسور|كسر)/i.test(message))return{concept:"fraction-foundation",confidence:.97,answer:"نبدأ من الأساس بدل ما نحاول نحفظ القواعد. الكسر يصف أجزاء متساوية من شيء كامل: في 1/2، الرقم 2 يقول إن الكل انقسم إلى جزأين متساويين، والرقم 1 يقول إننا أخذنا جزءًا واحدًا. خلّنا نشخّصها بسؤال صغير: لو قسمنا بيتزا إلى 4 قطع متساوية وأخذنا قطعة واحدة، أي كسر يمثل القطعة؟"};
 if(/ما معنى|اشرح.*(?:بسط|مقام)/.test(message))return{concept:"fraction-parts",confidence:.95,answer:"المقام يخبرنا إلى كم جزء متساوٍ قُسم الكل، والبسط يخبرنا كم جزءًا أخذنا أو نتحدث عنه. مثال: 3/4 يعني أن الكل مقسم إلى 4 أجزاء متساوية وأخذنا 3 منها."};
 if(docs.length&&/اشرح|فهم|وضح/.test(message))return{concept:"retrieved-concept",confidence:.8,answer:`خلّنا نبني الفكرة من معناها: ${docs[0].content.slice(0,500)}`};
 return null;
}