import {solveDeterministicMath,verifyMathAnswer} from "./math-engine";import {pedagogyPolicy} from "./pedagogy";import {createModelProvider,type HessaModelProvider} from "./provider";import {retrieveRelevant} from "./retrieval";import {routeSubject} from "./router";import {planDialogue} from "./dialogue-policy";import {teachKnownConcept} from "./concept-tutor";import {chooseTutorPhase,phaseInstruction} from "./tutor-state";import {critiqueTutorAnswer} from "./response-critic";import {buildLearningVisual} from "./learning-visuals";import type {TutorRequest,TutorResponse,VerificationResult} from "./types";import {validateTutorOutput} from "./tutor-output-validator";
export class HessaAICore{
 constructor(private readonly provider:HessaModelProvider=createModelProvider()){}
 async tutor(request:TutorRequest):Promise<TutorResponse>{
  const message=request.message?.trim();if(!message)throw new Error("message is required");
  const subject=routeSubject(message,request.subject);const pedagogy=pedagogyPolicy(request.student);const plan=planDialogue(message,request.history,request.student);const tutorPhase=chooseTutorPhase(request.mastery);
  const documents=retrieveRelevant(`${request.lessonTitle??""} ${plan.resolvedMessage}`,request.retrievedContext??[]);
  const deterministic=subject==="MATH"?solveDeterministicMath(plan.resolvedMessage):null;const concept=subject==="MATH"?teachKnownConcept(message,request.student,documents):null;let answer:string;let verification:VerificationResult;
  if(concept&&(plan.mode==="CONCEPT_EXPLANATION"||plan.mode==="SUPPORT_AND_DIAGNOSE")){answer=concept.answer;verification={verified:true,confidence:concept.confidence,method:"concept-curriculum-engine",issues:[]};}
  else if(deterministic&&plan.mode==="SOCRATIC_HINT"){
    answer=buildHint(message);verification={verified:true,confidence:.95,method:"verified-problem-hidden-answer",expectedAnswer:deterministic.expectedAnswer,issues:[]};
  }else if(deterministic){
    answer=adaptDeterministicAnswer(message,deterministic.answer,plan.mode,plan.shouldCheckUnderstanding);verification=verifyMathAnswer(plan.resolvedMessage,deterministic.answer);
  }else{
    const system=["أنت مدرس حصة الذكي، مدرس شخصي تفاعلي وليس آلة إجابات.",`المادة: ${subject}. المرحلة: ${pedagogy.stage}.`,...pedagogy.rules,...plan.instructions,phaseInstruction(tutorPhase),plan.priorContext?"استخدم سياق الحوار السابق لحل الإشارات والمتابعة، ولا تتظاهر بأن الرسالة مستقلة.":"",documents.length?"التزم بالمحتوى المسترجع ولا تخترع حقائق غير موجودة فيه.":"إذا لم تتوفر معرفة موثوقة فلا تخمّن."].filter(Boolean).join("\n");
    answer=await this.provider.generate({system,user:plan.resolvedMessage,context:documents.map(d=>d.content),history:request.history});
    if(subject==="MATH"){const expected=solveDeterministicMath(message)?.expectedAnswer;const previous=(request.history??[]).filter(x=>x.role==="assistant").map(x=>x.content);const gate=validateTutorOutput({userText:message,response:answer,knownAnswer:expected,previousResponses:previous});if(!gate.ok){const repair=[...system.split("\n"),"الرد السابق رُفض آليًا قبل عرضه للطالب.",...gate.policy.issues.map(x=>`سبب الرفض: ${x.code}. ${x.detail}`),...gate.math.errors.map(x=>`خطأ حسابي: ${x.expression} والصحيح ${x.actual}`),"أعد صياغة الرد من الصفر. لا تكرر النص المرفوض، ولا تكشف الإجابة إذا كان الطالب طلب تلميحًا."].join("\n");const regenerated=await this.provider.generate({system:repair,user:plan.resolvedMessage,context:documents.map(d=>d.content),history:request.history});const gate2=validateTutorOutput({userText:message,response:regenerated,knownAnswer:expected,previousResponses:previous});if(gate2.ok)answer=regenerated;else answer=safeTutorFallback(message,plan.mode,expected)}}
    verification=subject==="MATH"?verifyMathAnswer(plan.resolvedMessage,answer):{verified:documents.length>0,confidence:documents.length>0?.72:.3,method:documents.length>0?"retrieval-grounding":"unverified-generation",issues:documents.length>0?[]:["لا توجد مادة منهجية مسترجعة للتحقق من الإجابة."]};
  }
  const previousAssistant=[...(request.history??[])].reverse().find(x=>x.role==="assistant")?.content;const critique=critiqueTutorAnswer({message,answer,stage:pedagogy.stage,mode:plan.mode,verified:verification.verified,previousAssistant});if(!critique.pass&&critique.issues.includes("repeated-explanation")&&concept)answer=concept.answer+"\n\nخلّنا نغيّر طريقة التفكير بدل تكرار الخطوات السابقة.";
  const visual=buildLearningVisual(message);
  return{success:true,engine:"Hessa AI Core",version:"1.0.0",subject,stage:pedagogy.stage,answer,verification,context:{documentIds:documents.map(d=>d.id),grounded:documents.length>0},pedagogy:{maxSteps:pedagogy.maxSteps,language:"ar",dialect:pedagogy.dialect,rules:pedagogy.rules},metadata:{generatedAt:new Date().toISOString(),provider:deterministic?"deterministic-math":this.provider.name,tutorPhase,critiqueScore:critique.score,critiqueIssues:critique.issues,visual}};
 }
}
function buildHint(message:string){const expr=message.match(/(-?\d+(?:\.\d+)?)\s*([+\-×*÷/])\s*(-?\d+(?:\.\d+)?)/);if(expr){const op=expr[2];if(op==="÷"||op==="/")return`ما راح أكشف الناتج. فكّر بالعكس: أي عدد إذا ضربناه في ${expr[3]} يعطينا ${expr[1]}؟ جرّب خطوة واحدة واكتب لي العدد الذي تتوقعه.`;if(op==="×"||op==="*")return`ما راح أكشف الناتج. مثّل ${expr[1]} مجموعات، في كل مجموعة ${expr[3]} عناصر، ثم عدّ العناصر كلها. كم تتوقع؟`;}return"خلّنا نحلها سوا بدون كشف الجواب. ما أول معلومة تعرفها، وما العملية التي تعتقد أننا نحتاجها؟";}
function adaptDeterministicAnswer(message:string,base:string,mode:string,check:boolean){let answer=base;if(mode==="VERIFY_STUDENT_WORK"){if(/صح|صحيح/.test(message)&&/\//.test(message)&&!base.includes("غير صحيح"))base="حلك غير صحيح. "+base;const claim=message.match(/=\s*([^،؟?\s]+)/);const expected=base.match(/(?:الناتج(?: النهائي)? هو|يصبح|=)\s*([^\.،\s]+)/)?.[1];if(claim&&expected&&claim[1]!==expected)answer=`حلك غير صحيح، لكن الفكرة قابلة للتصحيح. ${base} الخطأ كان في طريقة تنفيذ العملية، وليس في أنك حاولت الحل.`;}if(mode==="CONCEPT_EXPLANATION"&&/مثلث|مساح/.test(message))answer="السبب أن المثلث يمثل نصف مستطيل له القاعدة والارتفاع نفسيهما. لو رسمنا مستطيلًا ثم قسمناه بقطر، نحصل على مثلثين متساويين؛ لذلك نأخذ نصف القاعدة × الارتفاع. "+base;if(check&&!/[؟?]\s*$/.test(answer))answer+="\n\nللتأكد أن الفكرة واضحة: هل تريد أن تجرب مثالًا مشابهًا بنفسك؟";return answer;}
function safeTutorFallback(message:string,mode:string,expected?:string){if(mode==="SOCRATIC_HINT")return"ما راح أكشف الناتج. خلّنا نأخذ خطوة واحدة فقط: حدّد العملية أو العلاقة العكسية المناسبة، واكتب لي محاولتك.";if(mode==="RETEACH")return"خلّنا نغيّر التمثيل بدل تكرار الشرح السابق. مثّل المسألة برسم أو مجموعات أو أجزاء متساوية، ثم قل لي ماذا تلاحظ أولًا.";if(mode==="VERIFY_STUDENT_WORK")return"خلّنا نتحقق من محاولتك خطوة خطوة قبل الحكم النهائي. اكتب العملية التي استخدمتها في آخر خطوة.";return expected?`خلّنا نتحقق خطوة خطوة بدل القفز للناتج. ما أول خطوة تقدر تبررها؟`:"خلّنا نمشي خطوة خطوة، ونتأكد من كل خطوة قبل الانتقال للي بعدها."}
