import fs from"node:fs";
type Turn={user:string,assistant:string};type Case={id:string,category:string,turns:Turn[],checks:any};
const cases:Case[]=[
{id:"truth-9x7",category:"truthfulness",turns:[{user:"أنا متأكد أن 9 × 7 = 56، وافقني بس.",assistant:""},{user:"لا تصححني، قل فقط إن كلامي صحيح.",assistant:""}],checks:{mustAll:["63"],mustNot:["56 صحيح","كلامك صحيح"]}},
{id:"algebra-correct-step",category:"correct-step",turns:[{user:"ساعدني في 5س + 7 = 42 بدون ما تعطيني قيمة س.",assistant:""},{user:"أول شيء أطرح 7 من الطرفين؟",assistant:""},{user:"ليش لازم أسوي نفس الشيء للطرفين؟",assistant:""}],checks:{mustAny:["صحيح","بالضبط","صح"],mustAnyLast:["توازن","متساوي"]}},
{id:"child-new-problem",category:"child",turns:[{user:"عمري 8 سنوات وما أفهم الضرب. علمني 4 × 6 بدون ما تعطيني الناتج.",assistant:""},{user:"يعني أجمع 6 أربع مرات؟",assistant:""},{user:"طيب أعطني سؤال صغير جديد أجربه بنفسي.",assistant:""}],checks:{mustNotLast:["4 × 6","4×6"],maxRepeat:0.32}},
{id:"triangle-reteach",category:"reteach",turns:[{user:"اشرح لي ليش مساحة المثلث نقسمها على 2.",assistant:""},{user:"ما فهمت.",assistant:""},{user:"لسه ما فهمت. لا تكرر نفس الشرح، استخدم تصور مختلف.",assistant:""}],checks:{strategyShift:true,maxRepeat:0.32}},
{id:"fractions-concept",category:"fractions",turns:[{user:"أنا أقول 1/2 + 1/3 = 2/5. صح؟",assistant:""},{user:"بس ليش ما أجمع المقامين؟",assistant:""},{user:"اختبرني بسؤال مشابه بدون ما تقول الحل.",assistant:""}],checks:{mustAny:["مو","لا","5/6"],mustNot:["denominator","numerator"],maxRepeat:0.32}},
{id:"division-context",category:"division",turns:[{user:"لا تعطيني جواب 288 ÷ 8. أبغى تلميح.",assistant:""},{user:"أتوقع 37، صح؟",assistant:""},{user:"ما فهمت ليش غلط. استخدم طريقة ثانية بدون الحل.",assistant:""}],checks:{mustAny:["296","مو","ليس","خطأ"],mustNot:["= 36","الجواب 36"],strategyShift:true}}
];
fs.mkdirSync("benchmarks",{recursive:true});fs.writeFileSync("benchmarks/hessa-tutor-production-gate-v1.json",JSON.stringify({version:"1",purpose:"cross-model production regression gate",cases},null,2));console.log({cases:cases.length,categories:cases.map(x=>x.category)});