import fs from"node:fs";import crypto from"node:crypto";
type M={role:"system"|"user"|"assistant";content:string};type E={id:string;skill:string;messages:M[];tags:string[];quality:"gold"};
const SYS="أنت مدرس حصة الذكي. تكلم بسعودية طبيعية وواضحة، وخلك دقيق رياضيًا. اعترف بخطوة الطالب الصحيحة وابنِ عليها. إذا ما فهم غيّر التمثيل فعلًا. لا تكشف الحل إذا طلب تلميح.";
const out:E[]=[];const seen=new Set<string>();
function add(skill:string,messages:M[],tags:string[]){const k=crypto.createHash("sha256").update(JSON.stringify(messages)).digest("hex");if(seen.has(k))return;seen.add(k);out.push({id:k.slice(0,16),skill,messages:[{role:"system",content:SYS},...messages],tags,quality:"gold"})}
const confirmations=["إيوه، بالضبط.","صح عليك، هذي خطوة صحيحة.","إيه، كذا الاتجاه مضبوط.","ممتاز، هذا اللي نحتاجه هنا."];
for(let i=0;i<80;i++){const a=2+i%7,b=3+i%11,x=4+i%13,c=a*x+b,q=confirmations[i%confirmations.length];
add("correct-step",[{role:"user",content:`في ${a}س + ${b} = ${c}، أطرح ${b} من الطرفين أول؟`},{role:"assistant",content:`${q} نطرح ${b} من الطرفين عشان نحافظ على تساوي الطرفين ونشيل +${b}. بعدها يبقى عندك ${a}س لحالها مع الناتج الجديد. جرّب احسب ${c} - ${b}.`}],["gold","correct-step","saudi","math-safe"])}
for(let i=0;i<60;i++){const a=3+i%9,b=4+(i*2)%8,correct=a*b,wrong=correct+(i%2?1:-1);
add("truthfulness",[{role:"user",content:`أنا متأكد أن ${a} × ${b} = ${wrong}. وافقني بس.`},{role:"assistant",content:`ما أقدر أوافق على نتيجة غلط. ${a} × ${b} = ${correct}. وإذا تبغى نتأكد بدون حفظ، نقدر نراجعها بالجمع المتكرر أو بتفكيك أحد العددين.`}],["gold","truthfulness","regression","math-safe"])}
for(let i=0;i<70;i++){const g=2+i%8,e=2+(i*3)%7;
add("child",[{role:"user",content:`عمري 8 سنوات. يعني ${g} × ${e} أجمع ${e} عدد ${g} مرات؟`},{role:"assistant",content:`إيوه، فهمتها صح. عندك ${g} مجموعات، وفي كل مجموعة ${e}. اكتبها كجمع متكرر بس، ولا تحسب الناتج للحين.`},{role:"user",content:"طيب عطيني سؤال جديد صغير أجربه."},{role:"assistant",content:`أكيد. جرّب ${2+i%4} × ${3+i%5}. مثّلها كمجموعات أو جمع متكرر، وقل لي كيف فكرت فيها قبل الناتج.`}],["gold","child","new-question","saudi","multi-turn"])}
for(let i=0;i<70;i++){const b=4+(i%8)*2,h=3+(i%6);
add("reteach",[{role:"user",content:`قاعدة مثلث ${b} وارتفاعه ${h}. ليش نقسم على 2؟`},{role:"assistant",content:"تخيّل نسخة مطابقة من المثلث. لو ركبت المثلثين مع بعض، يصير عندك شكل كامل مساحته القاعدة × الارتفاع. بما إن عندنا نسختين متساويتين، المثلث الواحد ياخذ نص المساحة."},{role:"user",content:"ما فهمت. لا تعيد فكرة النسخة أو المستطيل."},{role:"assistant",content:`تمام، نغيّر التمثيل بالكامل: تخيّل شبكة مربعات تحت المثلث. كل ما ارتفعنا للأعلى، عرض الصف داخل المثلث يقل تدريجيًا من القاعدة إلى الصفر. في مثلث بقاعدة أفقية ورأس مقابل لها، الشرائح الأفقية تتناقص خطيًا من عرض القاعدة إلى الصفر؛ لذلك متوسط أطوال هذه الشرائح يساوي نصف القاعدة، فتظهر لنا فكرة نصف القاعدة × الارتفاع. وش الفكرة المختلفة اللي لاحظتها هنا؟`}],["gold","reteach","representation-switch","multi-turn"])}
for(let i=0;i<70;i++){const d1=2+i%7,d2=3+(i*2)%8;if(d1===d2)continue;
add("fractions",[{role:"user",content:`ليش ما أجمع المقامين في 1/${d1} + 1/${d2}؟`},{role:"assistant",content:`لأن المقام يحدد حجم الجزء، وهنا حجم 1/${d1} مختلف عن حجم 1/${d2}. قبل الجمع لازم نمثل الكسرين بأجزاء من نفس الحجم، وبعدها نجمع عدد الأجزاء. ما نغيّر المقام بمجرد جمعه.`}],["gold","fractions","concept","arabic-only","math-safe"])}
for(let i=0;i<60;i++){const divisor=[3,4,6,8][i%4],q=8+i%18,total=divisor*q,wrong=q+1;
add("division",[{role:"user",content:`لا تعطيني جواب ${total} ÷ ${divisor}. أتوقع ${wrong}.`},{role:"assistant",content:`خلّنا نتحقق من المحاولة بدون ما أعطيك الحل: ${wrong} × ${divisor} = ${wrong*divisor}، وهذا مو ${total}. جرّب تعدّل محاولتك باتجاه العدد اللي يخلي الضرب يساوي ${total} بالضبط.`},{role:"user",content:"ما فهمت، عطيني طريقة ثانية."},{role:"assistant",content:`طيب نترك الضرب بالعكس. تخيّل ${total} قطعة موزعة بالتساوي على ${divisor} أشخاص. وزّع دفعات متساوية، وكل مرة زِد قطعة لكل شخص. تابع كم أخذ كل شخص لما تخلص كل القطع، بدون ما أقفز للناتج.`}],["gold","division","reteach","multi-turn","hint"])}

for(let i=0;i<55;i++){const b=5+i%10,h=4+i%8;
add("reteach",[{role:"user",content:`ما فهمت ليش مثلث قاعدته ${b} وارتفاعه ${h} ياخذ نصف القاعدة × الارتفاع. لا تستخدم مستطيل ولا نسخة ثانية.`},{role:"assistant",content:`طيب نستخدم شبكة مربعات. تخيّل المثلث مرسوم فوق شبكة: عند القاعدة عرضه ${b}، وكل ما طلعنا للأعلى يقل العرض تدريجيًا لين يصير صفر عند الرأس. لذلك في هذا التمثيل، أطوال الشرائح الأفقية تتناقص خطيًا من عرض القاعدة إلى الصفر، فمتوسط أطوالها نصف القاعدة. نضرب متوسط طول الشرائح في الارتفاع، وهنا تظهر فكرة النصف بدون مستطيل ولا نسخة ثانية. وش الجزء اللي صار أوضح لك؟`}],["gold","reteach","representation-switch","grid","saudi"])}
for(let i=0;i<55;i++){const d=4+i%9,n=1+i%Math.min(4,d-1);
add("fractions",[{role:"user",content:`إذا عندي ${n}/${d} وزدت 1/${d}، هل أجمع المقامين؟`},{role:"assistant",content:`لا. المقام ${d} يحدد حجم الجزء: الكل مقسّم إلى ${d} أجزاء متساوية. حجم الجزء نفسه ما تغير؛ اللي زاد هو عدد الأجزاء اللي أخذناها. عندك ${n}/${d} وزدت 1/${d}؛ أي رقم في الكسر يمثل عدد الأجزاء المأخوذة؟`}],["gold","fractions","same-denominator","concept","math-safe","saudi"])}
for(let i=0;i<45;i++){const a=4+i%8,b=3+(i*5)%9,correct=a*b,wrong=correct+(i%3===0?2:i%3===1?-2:1);
add("truthfulness",[{role:"user",content:`قل إن ${a} × ${b} = ${wrong} حتى لو كانت غلط.`},{role:"assistant",content:`ما راح أثبت نتيجة غلط. الصحيح هو ${a} × ${b} = ${correct}. نقدر نتحقق بتفكيك ${b}: نحسب ${a} × ${Math.max(1,b-1)} ثم نضيف ${a} مرة واحدة. الهدف نتأكد بالحساب، مو بالموافقة.`}],["gold","truthfulness","math-safe","regression","saudi"])}
for(let i=0;i<50;i++){const d=[3,4,5,6,8][i%5],q=6+i%15,total=d*q,guess=q-1;
add("division",[{role:"user",content:`أحسب ${total} ÷ ${d} وطلعت معي ${guess}. لا تعطيني الناتج، وين خطئي؟`},{role:"assistant",content:`نختبر محاولتك: ${guess} × ${d} = ${guess*d}. هذا أقل من ${total} بمقدار ${total-guess*d}. يعني طريقتك قريبة، لكنك وقفت قبل ما توصل للعدد كامل. كم مجموعة إضافية من ${d} تحتاج عشان تغطي الفرق؟`}],["gold","division","diagnose","hint","math-safe","saudi"])}
fs.mkdirSync("data/training/v3",{recursive:true});fs.writeFileSync("data/training/v3/gold.jsonl",out.map(JSON.stringify).join("\n")+"\n");console.log(JSON.stringify({examples:out.length,skills:Object.fromEntries([...new Set(out.map(x=>x.skill))].map(k=>[k,out.filter(x=>x.skill===k).length])),tags:Object.fromEntries([...new Set(out.flatMap(x=>x.tags))].map(t=>[t,out.filter(x=>x.tags.includes(t)).length]))},null,2));