import fs from"node:fs";import crypto from"node:crypto";
const read=(p:string)=>fs.readFileSync(p,"utf8").trim().split("\n").filter(Boolean).map(JSON.parse);
const v1=read("data/training/v1/train.jsonl"),v2=read("data/training/v2/hard-corrections.jsonl");
const benchmarkFiles=["scripts/tutor-professional-ux-eval.ts","scripts/long-dialogue-eval.ts","scripts/specialized-science-eval.ts"];const heldout=benchmarkFiles.filter(fs.existsSync).map(p=>fs.readFileSync(p,"utf8")).join("\n");
const unique=new Map<string,any>();for(const x of [...v1,...v2]){const key=crypto.createHash("sha256").update(JSON.stringify(x.messages)).digest("hex");const users=x.messages.filter((m:any)=>m.role==="user").map((m:any)=>m.content);if(users.some((u:string)=>heldout.includes(u)))continue;unique.set(key,x)}
const all=[...unique.values()];const groups=new Map<string,any[]>();for(const x of all){const k=x.skill??"unknown";if(!groups.has(k))groups.set(k,[]);groups.get(k)!.push(x)}
const train:any[]=[],validation:any[]=[];for(const [skill,items] of groups){items.sort((a,b)=>crypto.createHash("sha256").update(a.id).digest("hex").localeCompare(crypto.createHash("sha256").update(b.id).digest("hex")));const n=Math.max(10,Math.round(items.length*.1));validation.push(...items.slice(0,n));train.push(...items.slice(n));}
fs.mkdirSync("data/training/v2/combined",{recursive:true});fs.writeFileSync("data/training/v2/combined/train.jsonl",train.map(JSON.stringify).join("\n")+"\n");fs.writeFileSync("data/training/v2/combined/validation.jsonl",validation.map(JSON.stringify).join("\n")+"\n");
const countTag=(t:string)=>all.filter((x:any)=>(x.tags??[]).includes(t)).length;const skillCounts=Object.fromEntries([...groups].map(([k,v])=>[k,v.length]));const validationSkills=Object.fromEntries([...new Set(validation.map(x=>x.skill))].map(k=>[k,validation.filter(x=>x.skill===k).length]));
const result={v1:v1.length,v2:v2.length,combined:all.length,train:train.length,validation:validation.length,saudi:countTag("saudi"),multi:countTag("multi-turn"),reteach:countTag("representation-switch"),correct:countTag("correct-step"),misconception:countTag("misconception"),skillCounts,validationSkills,benchmarkLeakage:all.filter((x:any)=>x.messages.filter((m:any)=>m.role==="user").some((m:any)=>heldout.includes(m.content))).length};console.log(JSON.stringify(result,null,2));
if(v2.length<2500||result.saudi<2500||result.multi<500||result.reteach<500||result.correct<500||result.misconception<500||validation.length<500||result.benchmarkLeakage!==0)process.exitCode=1;